### PR TITLE
Documentation on bluepy installation with venv and SteamVR usage

### PR DESCRIPTION
**Pull request by DidierLoiseau**
Since I had to update my setup with the last versions of Ubuntu, I thought I would add it to the documentation here, as well as some tips for using lh2ctrl with SteamVR.

### CODE REVIEW

**Comment by risa2000** [comment]
Hello there, thanks for the patch!
I just changed some wording to make it more streamlined.

**Comment by DidierLoiseau** [comment]
I’m not sure “`SteamVR` binary _launch options_” is going to be very clear (you are not dealing with the binary, just with a Steam option) but I guess Linux Steam players will know their way.

This made me curious about your setup: you are running this tool from a Raspberry Pi, and using the HMD with a Windows PC?

**Comment by risa2000** [comment]
> I’m not sure “`SteamVR` binary _launch options_” is going to be very clear (you are not dealing with the binary, just with a Steam option) but I guess Linux Steam players will know their way.

I did take a shortcut and might have cut too much :). What is exactly launching as `%command%` by *launch options* and to which object are those *launch options* attributed? I am not looking for the particular implementation in particular linux distro, but the abstract definition.

> 
> This made me curious about your setup: you are running this tool from a Raspberry Pi, and using the HMD with a Windows PC?

Yes. This is how I use it.

**Comment by DidierLoiseau** [comment]
> What is exactly launching as `%command%` by _launch options_ and to which object are those _launch options_ attributed?

`%command%` is the command that Steam uses to launch the app. Any application in your Steam library can have specific _launch options_ (Steam library > right click on an app/game > properties > General > launch options) which allows to modify the way an app is launched. Here, specifically for SteamVR, I’m wrapping the default launch command between turning on&off the lighthouses. Nothing specific to Linux, actually, but AFAIK SteamVR takes care of the lighthouses automatically on Windows.

**Comment by risa2000** [comment]
> `%command%` is the command that Steam uses to launch the app. Any application in your Steam library can have specific _launch options_ (Steam library > right click on an app/game > properties > General > launch options) which allows to modify the way an app is launched. Here, specifically for SteamVR, I’m wrapping the default launch command between turning on&off the lighthouses. Nothing specific to Linux, actually, but AFAIK SteamVR takes care of the lighthouses automatically on Windows.

Then I guess I was not wrong :).

Just FYI, on Windows, SteamVR can start (or stop) the lighthouses automatically, but only when running with "supported" headsets. Which are HTC and Valve headsets mostly. For any exotics, you are out of luck. Plus I prefer to start lighthouses manually before my VR session so I could quit or restart SteamVR without disturbing them.

**Pull request merged**
