### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by robodrome**
Added usage example and note on bad bluetooth signal. Hope it helps others.

### CODE REVIEW

**Comment by risa2000** [comment]
@robodrome
Just out of curiosity, which RPi model do you run?

**Comment by robodrome** [comment]
@risa2000
It's not a Raspberry Pi device if that's what you mean. 

- It's a desktop PC motherboard, an ASUS ROG STRIX X570-E GAMING. 
- Before I connected the external (combined) WIFI/Bluetooth antenna the RSSI was worse than -103dBm (it couldn't find it).
- With the antenna connected the RSSI was -63dBm and it could find the lighthouses easily.
- On a Lenovo T490s placed close to the desktop PC, the signal RSSI was -57dBm, close to that of the desktop Bluetooth RSSI.

EDIT: added some clarification in antenna note in new commit.

Perhaps add some extra hints on signal strength in the readme to help other Bluetooth n00bs like me? ;-)

**Comment by risa2000** [comment]
@robodrome Do not worry about the wording I got the point :wink:.I was just wondering about your particular configuration. I know that RPi 4 for example has pretty bad BT reception because of USB 3.0 which is a massive source of interference. (Older RPi 2/3 are fine). The casing is another issue with an integrated antenna. So this is definitely good point to raise.

The example how to figure out the right MACs is a good one too. I might even expand on it a bit (have to check my other project for LHv1).

**Comment by robodrome** [comment]
@risa2000 Glad I could help a bit. In the [LHv1 repo](https://github.com/risa2000/lhctrl) you also demonstrate the `gatttool`. Nice. Thanks for your efforts on these projects. It really makes using the Valve Index on Linux easier.

**Pull request merged**
